import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const component = readFileSync(resolve('src/components/settings/SessionRecordingSettings.vue'), 'utf8');
const api = readFileSync(resolve('src/services/sessionRecording.api.ts'), 'utf8');
const dialogDrag = readFileSync(resolve('src/composables/useDraggableDialog.ts'), 'utf8');

assert.match(api, /SessionRecordingListQuery/);
assert.match(api, /SessionRecordingListPage/);
assert.match(component, /filterQuery/);
assert.match(component, /filterStatus/);
assert.match(component, /currentPage/);
assert.match(component, /timelineOffset/);
assert.match(component, /seekTo/);
assert.match(component, /cachedEvents/);
assert.match(component, /ResizeObserver/);
assert.match(api, /async delete\(/);
assert.match(api, /signal\?: AbortSignal/);
assert.match(component, /AbortController/);
assert.match(component, /nextEventCursor/);
assert.match(component, /MAX_CACHED_EVENTS\s*=\s*1000/);
assert.doesNotMatch(component, /while \(cursor !== null\)/);
assert.match(component, /recording-modal/);
assert.match(component, /deleteRecording/);
assert.match(component, /sessionRecording\.confirmDelete/);
assert.match(component, /timelineOffset\.value >= lastOffset/);
assert.match(component, /seekTo\(0\)/);
assert.match(component, /playbackDurationMs/);
assert.match(component, /cachedEvents\.value\[cachedEvents\.value\.length - 1\]\?\.offsetMs/);
assert.match(component, /:max="Math\.max\(1, playbackDurationMs\)"/);
assert.match(component, /class="recording-primary"/);
assert.match(component, /class="recording-owner"/);
assert.match(component, /class="recording-state"/);
assert.match(component, /recordedTerminalSize/);
assert.match(component, /syncTerminalViewport/);
assert.match(component, /primeTerminalForReplay/);
assert.match(component, /cachedEvents\.value\.find\(event => event\.type === 'resize'\)/);
assert.doesNotMatch(component, /style\.transform = `scale\(/);
assert.match(component, /grid-template-rows:auto auto minmax\(0,1fr\) auto/);
assert.match(component, /@media\(max-width:640px\)/);
assert.match(component, /useDraggableDialog/);
assert.match(component, /recording-drag-handle/);
assert.match(component, /box-sizing:border-box/);
assert.doesNotMatch(component, /\.recording-modal \.terminal-host\{min-height:12rem\}/);
assert.match(dialogDrag, /setPointerCapture/);
assert.match(dialogDrag, /maxLeft/);
assert.match(dialogDrag, /pointercancel/);

console.log('session recording workspace behavior ok');
